apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: airflow
resources:
  - ../../base/airflow
  - airflow-fernet-key.yaml
  - airflow-webserver-secret.yaml
  - airflow-worker-secrets.yaml
  - redis-password.yaml
  # - comdirect-data.yaml
