apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: kube-prometheus-stack-admin-pw
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/apps/items/kube-prometheus-stack-admin-pw"
