apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../../base/kube-prometheus-stack/
  - ingress.yaml
  - admin-pw-secret.yaml

patchesStrategicMerge:
  - release-overlay.yaml
