apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding
resources:
  - ../../base/linkding
  - linkding-container-env-secret.yaml
  # - cloudflare.yaml
  # - cloudflare-secret.yaml
  # - first-onepassword-secret.yaml

# https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#customizing
patchesStrategicMerge:
  - service_overlay.yaml
